# Base configs
baseurl:""

# UI configs
title: "Sahil Roy"
author: "Sahil Roy"
about: "sexy"
social_urls:
  facebook: "https://www.facebook.com/sahil.saspara"
  twitter: "#"
  instagram: "#"
mobile: "9879833433"
